language: generic
sudo: true
branches:
    only:
        - master
before_install:
    - bash ./scripts/build_travis.sh
    - pip install --user cpp-coveralls
install:       
    - hash -r
    - echo "Now try to build the module"
    - mkdir build 
    - cd build
    - cmake -DCOVERAGE=1 ..
    - make all
script:
    - pwd
    - ls
    - ./main
after_success:
    - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
